<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            // Osnovi Elektrotehnike
            [
                'title' => 'Osnovi Elektrotehnike 1',
                'author' => 'Milan Petrović',
                'publisher' => 'ETF Istočno Sarajevo',
                'published_year' => 2016,
                'edition' => '2',
                'description' => 'Uvod u elektrotehniku: otpornici, kola, Kirhofovi zakoni, analiza strujnih krugova.',
                'total_copies' => 5,
                'available_copies' => 5,
            ],
            [
                'title' => 'Osnovi Elektrotehnike 2',
                'author' => 'Milan Petrović',
                'publisher' => 'ETF Istočno Sarajevo',
                'published_year' => 2018,
                'edition' => '1',
                'description' => 'Naizmenične struje, kompleksne veličine, fazori, harmonijska analiza.',
                'total_copies' => 5,
                'available_copies' => 5,
            ],
            [
                'title' => 'Osnovi Elektrotehnike 3',
                'author' => 'Milan Petrović',
                'publisher' => 'ETF Istočno Sarajevo',
                'published_year' => 2019,
                'edition' => '1',
                'description' => 'Elektromagnetno polje, elektrostatika, magnetizam, indukcija.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],

            // Elektronika
            [
                'title' => 'Elektronski Elementi i Kola',
                'author' => 'Branimir Dolinar',
                'publisher' => 'ETF Beograd',
                'published_year' => 2014,
                'edition' => '4',
                'description' => 'Diode, tranzistori, pojačavači, operacioni pojačavači.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],
            [
                'title' => 'Analogna Elektronika',
                'author' => 'Dragan Djurić',
                'publisher' => 'ETF Beograd',
                'published_year' => 2017,
                'edition' => '1',
                'description' => 'Analogne komponente, filtri, stabilizatori i pojačavači.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],
            [
                'title' => 'Digitalna Elektronika',
                'author' => 'Zoran Uzelac',
                'publisher' => 'ETF Banja Luka',
                'published_year' => 2020,
                'edition' => '1',
                'description' => 'Logička kola, kombinatorna i sekvencijalna logika, brojni sistemi.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Elektronika Snage',
                'author' => 'Predrag Pejović',
                'publisher' => 'Akademska misao',
                'published_year' => 2018,
                'edition' => '2',
                'description' => 'Pretvarači, ispravljači, invertori, regulatori napona i struje.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Mikrokontroleri i Mikroprocesorski Sistemi',
                'author' => 'Dejan Ristić',
                'publisher' => 'ETF Niš',
                'published_year' => 2019,
                'edition' => '1',
                'description' => 'Arhitektura mikrokontrolera, programiranje, periferije, komunikacija.',
                'total_copies' => 5,
                'available_copies' => 5,
            ],
            [
                'title' => 'Programabilni Logički Kontroleri',
                'author' => 'Novak Stanković',
                'publisher' => 'Građevinska knjiga',
                'published_year' => 2017,
                'edition' => '1',
                'description' => 'PLC sistemi, ladder programiranje, industrijska automatika.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],

            // Programiranje
            [
                'title' => 'Programiranje u C jeziku',
                'author' => 'Kernighan & Ritchie',
                'publisher' => 'Mikro knjiga',
                'published_year' => 2008,
                'edition' => '3',
                'description' => 'Osnovna struktura C jezika, pokazivači, memorija, standardna biblioteka.',
                'total_copies' => 6,
                'available_copies' => 6,
            ],
            [
                'title' => 'Uvod u Algoritme i Strukture Podataka',
                'author' => 'Marko Marković',
                'publisher' => 'ETF Istočno Sarajevo',
                'published_year' => 2021,
                'edition' => '1',
                'description' => 'Liste, stabla, grafovi, sortiranje i pretrage.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],
            [
                'title' => 'Objektno Orijentisano Programiranje',
                'author' => 'Vladimir Filipović',
                'publisher' => 'CET',
                'published_year' => 2019,
                'edition' => '2',
                'description' => 'Klase, objekti, nasljeđivanje, polimorfizam, apstrakcija.',
                'total_copies' => 5,
                'available_copies' => 5,
            ],
            [
                'title' => 'Python za Početnike',
                'author' => 'Miloš Kovačević',
                'publisher' => 'Kompjuter biblioteka',
                'published_year' => 2020,
                'edition' => '1',
                'description' => 'Osnove Python-a, kontrolne strukture, funkcije, rad sa podacima.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],

            // Signali i Sistemi
            [
                'title' => 'Teorija Signala i Sistema',
                'author' => 'Zlatko Stanković',
                'publisher' => 'ETF Beograd',
                'published_year' => 2015,
                'edition' => '1',
                'description' => 'Kontinuirani i diskretni signali, transformacije i analiza.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Digitalna Obrada Signala',
                'author' => 'Alan V. Oppenheim',
                'publisher' => 'Mikro knjiga',
                'published_year' => 2016,
                'edition' => '2',
                'description' => 'Furijeove transformacije, filteri, obrada signala u realnom vremenu.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Obrada Govora i Slike',
                'author' => 'Nikola Teslić',
                'publisher' => 'FTN Novi Sad',
                'published_year' => 2018,
                'edition' => '1',
                'description' => 'Kompresija, prepoznavanje, digitalna obrada audio i video signala.',
                'total_copies' => 2,
                'available_copies' => 2,
            ],

            // Telekomunikacije
            [
                'title' => 'Telekomunikacioni Sistemi',
                'author' => 'Slobodan Miljanović',
                'publisher' => 'ETF Banja Luka',
                'published_year' => 2019,
                'edition' => '1',
                'description' => 'Modulacija, multipleksiranje, mreže, komunikacioni protokoli.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],
            [
                'title' => 'Bežične Komunikacije',
                'author' => 'Dragan Mitić',
                'publisher' => 'ETF Niš',
                'published_year' => 2020,
                'edition' => '1',
                'description' => 'Radio talasi, antene, mobilne mreže, 4G/5G tehnologije.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Optička Komunikaciona Tehnologija',
                'author' => 'Branko Kolundžija',
                'publisher' => 'ETF Beograd',
                'published_year' => 2017,
                'edition' => '2',
                'description' => 'Optička vlakna, laseri, multipleksiranje, optičke mreže.',
                'total_copies' => 2,
                'available_copies' => 2,
            ],
            [
                'title' => 'Računarske Mreže',
                'author' => 'Petar Knežević',
                'publisher' => 'Akademska misao',
                'published_year' => 2021,
                'edition' => '3',
                'description' => 'TCP/IP protokoli, Ethernet, routing, switching, mrežna bezbednost.',
                'total_copies' => 5,
                'available_copies' => 5,
            ],

            // Električne Mašine i Energetika
            [
                'title' => 'Električne Mašine',
                'author' => 'Božidar Filipović-Grčić',
                'publisher' => 'FER Zagreb',
                'published_year' => 2015,
                'edition' => '4',
                'description' => 'Transformatori, asinhroni i sinhroni motori, generatori.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],
            [
                'title' => 'Elektroenergetski Sistemi 1',
                'author' => 'Nikola Rajaković',
                'publisher' => 'ETF Beograd',
                'published_year' => 2018,
                'edition' => '2',
                'description' => 'Proizvodnja, prenos i distribucija električne energije.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Elektroenergetski Sistemi 2',
                'author' => 'Nikola Rajaković',
                'publisher' => 'ETF Beograd',
                'published_year' => 2019,
                'edition' => '1',
                'description' => 'Zaštita, regulacija, stabilnost elektroenergetskih sistema.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Obnovljivi Izvori Energije',
                'author' => 'Miodrag Despotović',
                'publisher' => 'ETF Podgorica',
                'published_year' => 2020,
                'edition' => '1',
                'description' => 'Solarna energija, vjetroelektrane, hidroelektrane, biomasa.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Visokonaponska Tehnika',
                'author' => 'Jovan Nahman',
                'publisher' => 'ETF Beograd',
                'published_year' => 2016,
                'edition' => '3',
                'description' => 'Izolatori, preskoci, gromobrani, zaštita od prenapona.',
                'total_copies' => 2,
                'available_copies' => 2,
            ],

            // Automatika i Upravljanje
            [
                'title' => 'Automatsko Upravljanje',
                'author' => 'Dragan Antić',
                'publisher' => 'ETF Niš',
                'published_year' => 2017,
                'edition' => '2',
                'description' => 'Povratna sprega, PID regulatori, stabilnost sistema.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],
            [
                'title' => 'Diskretni Sistemi Upravljanja',
                'author' => 'Čedomir Milosavljević',
                'publisher' => 'ETF Niš',
                'published_year' => 2019,
                'edition' => '1',
                'description' => 'Digitalna regulacija, Z-transformacija, diskretni algoritmi.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Industrijska Automatika',
                'author' => 'Miroslav Bjekić',
                'publisher' => 'Mašinski fakultet',
                'published_year' => 2018,
                'edition' => '1',
                'description' => 'Senzori, aktuatori, SCADA sistemi, procesno upravljanje.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Robotika',
                'author' => 'Miomir Vukobratović',
                'publisher' => 'Mikro knjiga',
                'published_year' => 2016,
                'edition' => '2',
                'description' => 'Kinematika, dinamika, senzori, programiranje robota.',
                'total_copies' => 2,
                'available_copies' => 2,
            ],

            // Mjerenja i Instrumentacija
            [
                'title' => 'Električna Mjerenja',
                'author' => 'Aleksandar Žigić',
                'publisher' => 'ETF Banja Luka',
                'published_year' => 2018,
                'edition' => '2',
                'description' => 'Mjerni instrumenti, tačnost, greške, metode mjerenja.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],
            [
                'title' => 'Elektronska Mjerenja',
                'author' => 'Branislav Dokić',
                'publisher' => 'ETF Banja Luka',
                'published_year' => 2019,
                'edition' => '1',
                'description' => 'Osciloskopi, generatori, analizatori, digitalna mjerenja.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Senzori i Pretvarači',
                'author' => 'Vančo Litovski',
                'publisher' => 'ETF Niš',
                'published_year' => 2017,
                'edition' => '3',
                'description' => 'Temperaturni, pritisni, optički senzori, A/D i D/A konverzija.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],

            // Matematika i Fizika
            [
                'title' => 'Matematika 1',
                'author' => 'Gradimir V. Milovanović',
                'publisher' => 'Naučna knjiga',
                'published_year' => 2015,
                'edition' => '5',
                'description' => 'Diferencijalini i integralni račun, funkcije više promjenljivih.',
                'total_copies' => 6,
                'available_copies' => 6,
            ],
            [
                'title' => 'Matematika 2',
                'author' => 'Gradimir V. Milovanović',
                'publisher' => 'Naučna knjiga',
                'published_year' => 2016,
                'edition' => '4',
                'description' => 'Diferencijalne jednačine, Laplaceova transformacija, vektorska analiza.',
                'total_copies' => 6,
                'available_copies' => 6,
            ],
            [
                'title' => 'Linearna Algebra',
                'author' => 'Branko Malešević',
                'publisher' => 'Građevinski fakultet',
                'published_year' => 2018,
                'edition' => '2',
                'description' => 'Matrice, determinante, vektori, karakteristične vrijednosti.',
                'total_copies' => 5,
                'available_copies' => 5,
            ],
            [
                'title' => 'Kompleksna Analiza',
                'author' => 'Radoslav Dimitrijević',
                'publisher' => 'Prirodno-matematički fakultet',
                'published_year' => 2017,
                'edition' => '1',
                'description' => 'Kompleksne funkcije, integrali, rezidue, konformna preslikavanja.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Fizika 1 - Mehanika',
                'author' => 'Slobodan Prvanović',
                'publisher' => 'Zavod za udžbenike',
                'published_year' => 2016,
                'edition' => '6',
                'description' => 'Kinematika, dinamika, rad, energija, oscilacije.',
                'total_copies' => 5,
                'available_copies' => 5,
            ],
            [
                'title' => 'Fizika 2 - Elektromagnetizam',
                'author' => 'Slobodan Prvanović',
                'publisher' => 'Zavod za udžbenike',
                'published_year' => 2017,
                'edition' => '5',
                'description' => 'Elektrostatika, magnetizam, elektromagnetna indukcija, Maxwellove jednačine.',
                'total_copies' => 5,
                'available_copies' => 5,
            ],

            //SpecijalizovANE OBLASTI
            [
                'title' => 'VLSI Dizajn',
                'author' => 'Veljko Milutinović',
                'publisher' => 'ETF Beograd',
                'published_year' => 2019,
                'edition' => '1',
                'description' => 'Projektovanje integrisanih kola, CMOS tehnologija, layout.',
                'total_copies' => 2,
                'available_copies' => 2,
            ],
            [
                'title' => 'Biomedicinska Elektronika',
                'author' => 'Dejan Popović',
                'publisher' => 'ETF Beograd',
                'published_year' => 2018,
                'edition' => '2',
                'description' => 'EKG, EEG, medicinski aparati, biosenzori, dijagnostika.',
                'total_copies' => 2,
                'available_copies' => 2,
            ],
            [
                'title' => 'Elektromagnetna Kompatibilnost',
                'author' => 'Nebojša Dončov',
                'publisher' => 'ETF Niš',
                'published_year' => 2019,
                'edition' => '1',
                'description' => 'EMC standardi, smetnje, zaštita, testiranje i certifikacija.',
                'total_copies' => 2,
                'available_copies' => 2,
            ],
            [
                'title' => 'Vještačka Inteligencija',
                'author' => 'Branko Milosavljević',
                'publisher' => 'Matematički fakultet',
                'published_year' => 2021,
                'edition' => '1',
                'description' => 'Mašinsko učenje, neuronske mreže, duboko učenje, primjene.',
                'total_copies' => 4,
                'available_copies' => 4,
            ],
            [
                'title' => 'Internet Stvari (IoT)',
                'author' => 'Goran Dimić',
                'publisher' => 'FTN Novi Sad',
                'published_year' => 2020,
                'edition' => '1',
                'description' => 'IoT arhitektura, senzori, cloud computing, pametni uređaji.',
                'total_copies' => 3,
                'available_copies' => 3,
            ],
            [
                'title' => 'Kvantne Komunikacije',
                'author' => 'Milica Stojanović',
                'publisher' => 'Institut za fiziku',
                'published_year' => 2020,
                'edition' => '1',
                'description' => 'Kvantna kriptografija, kvantni računari, fotonska komunikacija.',
                'total_copies' => 2,
                'available_copies' => 2,
            ],
        ];

        foreach ($books as $data) {
            Book::create($data);
        }
    }
}
