<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            // Semester I
            [
                'code'        => 'MAT-1',
                'name'        => 'Matematika - 1',
                'description' => 'Matematika - prvi semestar',
                'ects'        => 7.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'FIZ',
                'name'        => 'Fizika',
                'description' => 'Fizika',
                'ects'        => 6.5,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'OET-1',
                'name'        => 'Osnovi elektrotehnike - 1',
                'description' => 'Osnovi elektrotehnike - prvi semestar',
                'ects'        => 7.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ORT',
                'name'        => 'Osnovi racunarske tehnike',
                'description' => 'Osnovi racunarske tehnike',
                'ects'        => 5.5,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'UVM',
                'name'        => 'Uvod u menadzment',
                'description' => 'Uvod u menadzment',
                'ects'        => 2.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ENG-1',
                'name'        => 'Engleski jezik - 1',
                'description' => 'Engleski jezik - prvi semestar',
                'ects'        => 2.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],

            // Semester II
            [
                'code'        => 'MAT-2',
                'name'        => 'Matematika - 2',
                'description' => 'Matematika - drugi semestar',
                'ects'        => 7.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'UVP',
                'name'        => 'Uvod u programiranje',
                'description' => 'Uvod u programiranje',
                'ects'        => 5.5,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'OET-2',
                'name'        => 'Osnovi elektrotehnike - 2',
                'description' => 'Osnovi elektrotehnike - drugi semestar',
                'ects'        => 7.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'FOE',
                'name'        => 'Fizicki osnovi elektrotehnike',
                'description' => 'Fizicki osnovi elektrotehnike',
                'ects'        => 5.5,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'APS',
                'name'        => 'Aplikativni softver',
                'description' => 'Aplikativni softver',
                'ects'        => 3.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ENG-2',
                'name'        => 'Engleski jezik - 2',
                'description' => 'Engleski jezik - drugi semestar',
                'ects'        => 2.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],

            // Semester III
            [
                'code'        => 'MAT-3',
                'name'        => 'Matematika - 3',
                'description' => 'Matematika - treci semestar',
                'ects'        => 6.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'TEK-1',
                'name'        => 'Teorija elektricnih kola - 1',
                'description' => 'Teorija elektricnih kola - prvi semestar',
                'ects'        => 5.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ELM',
                'name'        => 'Elektricna mjerenja',
                'description' => 'Elektricna mjerenja',
                'ects'        => 5.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ELE-1',
                'name'        => 'Elektronika - 1',
                'description' => 'Elektronika - prvi semestar',
                'ects'        => 6.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'PRJ',
                'name'        => 'Programski jezici',
                'description' => 'Programski jezici',
                'ects'        => 6.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ENG-3',
                'name'        => 'Engleski jezik - 3',
                'description' => 'Engleski jezik - treci semestar',
                'ects'        => 2.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],

            // Semester IV
            [
                'code'        => 'NUM',
                'name'        => 'Numericka matematika',
                'description' => 'Numericka matematika',
                'ects'        => 6.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'TEK-2',
                'name'        => 'Teorija elektricnih kola - 2',
                'description' => 'Teorija elektricnih kola - drugi semestar',
                'ects'        => 5.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ELG-1',
                'name'        => 'Elektromagnetika - 1',
                'description' => 'Elektromagnetika - prvi semestar',
                'ects'        => 6.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ELE-2',
                'name'        => 'Elektronika - 2',
                'description' => 'Elektronika - drugi semestar',
                'ects'        => 5.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'OOP',
                'name'        => 'Objektno orijentisano programiranje',
                'description' => 'Objektno orijentisano programiranje',
                'ects'        => 6.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
            [
                'code'        => 'ENG-4',
                'name'        => 'Engleski jezik - 4',
                'description' => 'Engleski jezik - cetvrti semestar',
                'ects'        => 2.0,
                'department'  => 'Electrical Engineering',
                'level'       => 'bachelor',
                'mandatory'   => true,
                'status'      => 'active',
            ],
        ];

        foreach ($courses as $course) {
            Course::updateOrCreate(
                ['code' => $course['code']],
                $course
            );
        }
    }
}
